package:
  name: dev-andor3
  version: "{{ SETUPTOOLS_SCM_PRETEND_VERSION }}"

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - Andor3 = dev_andor3.Andor3:main

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - python
    - libdaq >=1.3.2
    - cffi
    - numpy
    - pytango
    - pyzmq
    
about:
  license: GPL-3.0-or-later
  license_file: ../LICENSE.txt

 
